services:
    # backend:
    #     build: ./backend
    #     ports:
    #         - "8080:8080"
    #     restart: always

    # frontend:
    #     build: ./frontend
    #     ports:

    db:
        image: postgres:15
        restart: always
        environment:
            - POSTGRES_DB=db
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
            
        

